# Generated by Django 5.2.7 on 2025-10-28 01:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteid', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('fecharegistro', models.DateTimeField(default=django.utils.timezone.now)),
                ('preferenciasgenero', models.CharField(choices=[('ficcion', 'Ficción'), ('ciencia_ficcion', 'Ciencia Ficción'), ('fantasia', 'Fantasía'), ('misterio', 'Misterio'), ('romance', 'Romance'), ('terror', 'Terror'), ('biografia', 'Biografía'), ('historia', 'Historia'), ('ciencia', 'Ciencia'), ('infantil', 'Infantil')], default='ficcion', max_length=50)),
                ('foto_cliente', models.ImageField(blank=True, null=True, upload_to='clientes_fotos/')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecharegistro'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('ventaid', models.AutoField(primary_key=True, serialize=False)),
                ('fechaventa', models.DateTimeField(default=django.utils.timezone.now)),
                ('montototal', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('metodopago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], default='efectivo', max_length=50)),
                ('estadoVenta', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reembolsada', 'Reembolsada')], default='pendiente', max_length=50)),
                ('descuentoAplicado', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app_libreria.cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fechaventa'],
            },
        ),
    ]
